apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-api-ingress
  namespace: bookstore
spec:
  rules:
    - host: bookstore.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookstore-api
                port:
                  number: 80
